[app]
name = "Hat Village"
category = "Badge"

[entry]
class = "HatVillage"

[metadata]
author = "pikesley"
license = "MIT"
url = "https://www.github.com/pikesley/tildagon-hat-village"
description = "The official app of Hat Village at EMF 2026"
version = "0.0.1"
